### ISSUE TITLE
Show Error in evedev

### ISSUE THREAD

**Issue by ghost** [elias19r/xkb-layouts#1]
It's Showing errors like this :-

xkbcommon: ERROR: /home/sgimres/.config/xkb/rules/evdev:1:3: unexpected token
xkbcommon: ERROR: No components returned from XKB rules "/home/sgimres/.config/xkb/rules/evdev"
xkbcommon: ERROR: Couldn't look up rules 'evdev', model 'pc105', layout 'us', variant '(null)', options '(null)'
Segmentation fault (core dumped)

im trying to use this on swaywm

**Comment by elias19r** [comment]
Hi, thank you for testing it! I haven't had the chance to test it on Wayland yet.

> config/xkb/rules/evdev:1:3: unexpected token

That's interesting. From the error message, it seems Wayland expects another format for that file.

Could you try removing the file `/home/sgimres/.config/xkb/rules/evdev` and keep only the XML file `/home/sgimres/.config/xkb/rules/evdev.xml`?

**Comment by elias19r** [comment]
Also, for comparison, please take a look at your system's XKB files. They may be in a directory called `/usr/share/X11/xkb/` or similar. See if they have a different format.

**Comment by ghost** [comment]
removing /home/sgimres/.config/xkb/rules/evdev wont fix it 
1. output after removing the file :-
00:00:00.021 [sway/input/keyboard.c:752] [xkbcommon] Cannot compile a xkb_symbols file alone into a keymap
00:00:00.021 [sway/config.c:857] Error on line 62 'xkb_file ~/.config/xkb/symbols/colemak_dh_ansi': Failed to compile keymap: Cannot compile a xkb_symbols file alone into a key map (/home/sgimres/.config/sway/config)
00:00:00.025 [sway/config.c:425] Error(s) loading config!

2. Yup it is totally different
[https://pastebin.com/raw/NN6W5Ear](url)

**Comment by elias19r** [comment]
Hmm, I see. So making this work on Wayland isn't as simple as copying files to `~/.config/xkb`. I'm thinking of removing that section from the README.

Could you remove those files from `~/.config/xkb` and then try the installation steps from the [X11 section of the README](https://github.com/elias19r/xkb-layouts/blob/f88d8677931ed1f04002768e41df2c1a4efde09d/README.md#x11)?

Let me know if that works.

**Comment by ghost** [comment]
I didn't need those layouts for x11 But Thank you for your time sir ... 😊
